const ACTIONS = {
  SCROLL_TO_REFERENCE: 'SCROLL_TO_REFERENCE',
  SET_JAVASCRIPT_OFFSET_TOP: 'SET_JAVASCRIPT_OFFSET_TOP',
  SET_TYPESCRIPT_OFFSET_TOP: 'SET_TYPESCRIPT_OFFSET_TOP',
  SET_REACT_OFFSET_TOP: 'SET_REACT_OFFSET_TOP',
  SET_GRAPHQL_OFFSET_TOP: 'SET_GRAPHQL_OFFSET_TOP'
};

const GENERAL_OFFSET = 100;

export {
  ACTIONS,
  GENERAL_OFFSET
};
